logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.provider.token: DEBUG

server:
  port: 9090
  
public_key: |   
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsfZE5kCZ9gKaRfFk6XEc
  blqRTxTlcgyTEKNaQmNCWTZJNmzDEQcMeSmDIVE3AqN1LUAWpbWLaRFhCB4CsPdC
  ztrjURr6aA7C82cgZmswS6gLnZvusMRvXt9sK3oco5JWSNy4H2jD03gj55Dy6CUF
  xEut6mwv35mvmreh6F7FbanBlFCmJ7iVXjlatfyvdttfe9uWsUre9r/qZTPSE2u1
  s86fjM2jgnA9D4U0F11kYy1lCn6qIHduY2S+OczOqPwWrh49EHjD8pnIiFxY7DmA
  Ob92zfEQpwvwbmqPB4sw9/pSRYs22s3Mid3vaGNbh/4cQjcEUR/c0sGm/702Gm5R
  HQIDAQAB
  -----END PUBLIC KEY-----